// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.27.0

package com.umut.yesevi.protobuf;

public final class PersonProtos {
  private PersonProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      PersonProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yesevi_PersonPro_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yesevi_PersonPro_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yesevi_PersonArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yesevi_PersonArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\006yesevi\"J\n\tPersonPro\022\014\n\004n" +
      "ame\030\001 \001(\t\022\020\n\010lastname\030\002 \001(\t\022\017\n\007address\030\003" +
      " \001(\t\022\014\n\004city\030\004 \001(\t\"0\n\013PersonArray\022!\n\006per" +
      "son\030\001 \003(\0132\021.yesevi.PersonProB*\n\030com.umut" +
      ".yesevi.protobufB\014PersonProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yesevi_PersonPro_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yesevi_PersonPro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yesevi_PersonPro_descriptor,
        new java.lang.String[] { "Name", "Lastname", "Address", "City", });
    internal_static_yesevi_PersonArray_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_yesevi_PersonArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yesevi_PersonArray_descriptor,
        new java.lang.String[] { "Person", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
