/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.umut.yesevi.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-02-16")
public class EmployeeList implements org.apache.thrift.TBase<EmployeeList, EmployeeList._Fields>, java.io.Serializable, Cloneable, Comparable<EmployeeList> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EmployeeList");

  private static final org.apache.thrift.protocol.TField EMPLOYEES_FIELD_DESC = new org.apache.thrift.protocol.TField("employees", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new EmployeeListStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new EmployeeListTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<EmployeeThrift> employees; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EMPLOYEES((short)1, "employees");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EMPLOYEES
          return EMPLOYEES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EMPLOYEES, new org.apache.thrift.meta_data.FieldMetaData("employees", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EmployeeThrift.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EmployeeList.class, metaDataMap);
  }

  public EmployeeList() {
  }

  public EmployeeList(
    java.util.List<EmployeeThrift> employees)
  {
    this();
    this.employees = employees;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EmployeeList(EmployeeList other) {
    if (other.isSetEmployees()) {
      java.util.List<EmployeeThrift> __this__employees = new java.util.ArrayList<EmployeeThrift>(other.employees.size());
      for (EmployeeThrift other_element : other.employees) {
        __this__employees.add(new EmployeeThrift(other_element));
      }
      this.employees = __this__employees;
    }
  }

  @Override
  public EmployeeList deepCopy() {
    return new EmployeeList(this);
  }

  @Override
  public void clear() {
    this.employees = null;
  }

  public int getEmployeesSize() {
    return (this.employees == null) ? 0 : this.employees.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<EmployeeThrift> getEmployeesIterator() {
    return (this.employees == null) ? null : this.employees.iterator();
  }

  public void addToEmployees(EmployeeThrift elem) {
    if (this.employees == null) {
      this.employees = new java.util.ArrayList<EmployeeThrift>();
    }
    this.employees.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<EmployeeThrift> getEmployees() {
    return this.employees;
  }

  public EmployeeList setEmployees(@org.apache.thrift.annotation.Nullable java.util.List<EmployeeThrift> employees) {
    this.employees = employees;
    return this;
  }

  public void unsetEmployees() {
    this.employees = null;
  }

  /** Returns true if field employees is set (has been assigned a value) and false otherwise */
  public boolean isSetEmployees() {
    return this.employees != null;
  }

  public void setEmployeesIsSet(boolean value) {
    if (!value) {
      this.employees = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case EMPLOYEES:
      if (value == null) {
        unsetEmployees();
      } else {
        setEmployees((java.util.List<EmployeeThrift>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case EMPLOYEES:
      return getEmployees();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case EMPLOYEES:
      return isSetEmployees();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof EmployeeList)
      return this.equals((EmployeeList)that);
    return false;
  }

  public boolean equals(EmployeeList that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_employees = true && this.isSetEmployees();
    boolean that_present_employees = true && that.isSetEmployees();
    if (this_present_employees || that_present_employees) {
      if (!(this_present_employees && that_present_employees))
        return false;
      if (!this.employees.equals(that.employees))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetEmployees()) ? 131071 : 524287);
    if (isSetEmployees())
      hashCode = hashCode * 8191 + employees.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(EmployeeList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetEmployees(), other.isSetEmployees());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEmployees()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.employees, other.employees);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("EmployeeList(");
    boolean first = true;

    sb.append("employees:");
    if (this.employees == null) {
      sb.append("null");
    } else {
      sb.append(this.employees);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EmployeeListStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public EmployeeListStandardScheme getScheme() {
      return new EmployeeListStandardScheme();
    }
  }

  private static class EmployeeListStandardScheme extends org.apache.thrift.scheme.StandardScheme<EmployeeList> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, EmployeeList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EMPLOYEES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.employees = new java.util.ArrayList<EmployeeThrift>(_list0.size);
                @org.apache.thrift.annotation.Nullable EmployeeThrift _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new EmployeeThrift();
                  _elem1.read(iprot);
                  struct.employees.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setEmployeesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, EmployeeList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.employees != null) {
        oprot.writeFieldBegin(EMPLOYEES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.employees.size()));
          for (EmployeeThrift _iter3 : struct.employees)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EmployeeListTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public EmployeeListTupleScheme getScheme() {
      return new EmployeeListTupleScheme();
    }
  }

  private static class EmployeeListTupleScheme extends org.apache.thrift.scheme.TupleScheme<EmployeeList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EmployeeList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetEmployees()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetEmployees()) {
        {
          oprot.writeI32(struct.employees.size());
          for (EmployeeThrift _iter4 : struct.employees)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EmployeeList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.employees = new java.util.ArrayList<EmployeeThrift>(_list5.size);
          @org.apache.thrift.annotation.Nullable EmployeeThrift _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new EmployeeThrift();
            _elem6.read(iprot);
            struct.employees.add(_elem6);
          }
        }
        struct.setEmployeesIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

