// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: employee/employee.proto
// Protobuf Java Version: 4.31.1

package com.umut.yesevi.protobuf;

@com.google.protobuf.Generated
public interface EmployeeProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yesevi.EmployeeProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double recid = 1;</code>
   * @return The recid.
   */
  double getRecid();

  /**
   * <code>float share = 2;</code>
   * @return The share.
   */
  float getShare();

  /**
   * <code>int32 jobcode = 3;</code>
   * @return The jobcode.
   */
  int getJobcode();

  /**
   * <code>string title = 4;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 4;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();
}
