// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: employee.proto
// Protobuf Java Version: 4.27.0

package com.umut.yesevi.protobuf;

public interface EmployeeProOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yesevi.EmployeePro)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double recid = 1;</code>
   * @return Whether the recid field is set.
   */
  boolean hasRecid();
  /**
   * <code>optional double recid = 1;</code>
   * @return The recid.
   */
  double getRecid();

  /**
   * <code>optional float share = 2;</code>
   * @return Whether the share field is set.
   */
  boolean hasShare();
  /**
   * <code>optional float share = 2;</code>
   * @return The share.
   */
  float getShare();

  /**
   * <code>optional int32 jobcode = 3;</code>
   * @return Whether the jobcode field is set.
   */
  boolean hasJobcode();
  /**
   * <code>optional int32 jobcode = 3;</code>
   * @return The jobcode.
   */
  int getJobcode();

  /**
   * <code>optional string title = 4;</code>
   * @return Whether the title field is set.
   */
  boolean hasTitle();
  /**
   * <code>optional string title = 4;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>optional string title = 4;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();
}
