// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: employee/employee.proto
// Protobuf Java Version: 4.31.1

package com.umut.yesevi.protobuf;

@com.google.protobuf.Generated
public interface EmployeeProtoArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yesevi.EmployeeProtoArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .yesevi.EmployeeProto employee = 1;</code>
   */
  java.util.List<com.umut.yesevi.protobuf.EmployeeProto> 
      getEmployeeList();
  /**
   * <code>repeated .yesevi.EmployeeProto employee = 1;</code>
   */
  com.umut.yesevi.protobuf.EmployeeProto getEmployee(int index);
  /**
   * <code>repeated .yesevi.EmployeeProto employee = 1;</code>
   */
  int getEmployeeCount();
  /**
   * <code>repeated .yesevi.EmployeeProto employee = 1;</code>
   */
  java.util.List<? extends com.umut.yesevi.protobuf.EmployeeProtoOrBuilder> 
      getEmployeeOrBuilderList();
  /**
   * <code>repeated .yesevi.EmployeeProto employee = 1;</code>
   */
  com.umut.yesevi.protobuf.EmployeeProtoOrBuilder getEmployeeOrBuilder(
      int index);
}
