// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: employee.proto
// Protobuf Java Version: 4.27.0

package com.umut.yesevi.protobuf;

public interface EmployeeArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yesevi.EmployeeArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .yesevi.EmployeePro employee = 1;</code>
   */
  java.util.List<com.umut.yesevi.protobuf.EmployeePro> 
      getEmployeeList();
  /**
   * <code>repeated .yesevi.EmployeePro employee = 1;</code>
   */
  com.umut.yesevi.protobuf.EmployeePro getEmployee(int index);
  /**
   * <code>repeated .yesevi.EmployeePro employee = 1;</code>
   */
  int getEmployeeCount();
  /**
   * <code>repeated .yesevi.EmployeePro employee = 1;</code>
   */
  java.util.List<? extends com.umut.yesevi.protobuf.EmployeeProOrBuilder> 
      getEmployeeOrBuilderList();
  /**
   * <code>repeated .yesevi.EmployeePro employee = 1;</code>
   */
  com.umut.yesevi.protobuf.EmployeeProOrBuilder getEmployeeOrBuilder(
      int index);
}
