// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: employee.proto
// Protobuf Java Version: 4.27.0

package com.umut.yesevi.protobuf;

public final class EmployeeProtos {
  private EmployeeProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      EmployeeProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yesevi_EmployeePro_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yesevi_EmployeePro_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yesevi_EmployeeArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yesevi_EmployeeArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016employee.proto\022\006yesevi\"K\n\013EmployeePro\022" +
      "\r\n\005recid\030\001 \001(\001\022\r\n\005share\030\002 \001(\002\022\017\n\007jobcode" +
      "\030\003 \001(\005\022\r\n\005title\030\004 \001(\t\"6\n\rEmployeeArray\022%" +
      "\n\010employee\030\001 \003(\0132\023.yesevi.EmployeeProB,\n" +
      "\030com.umut.yesevi.protobufB\016EmployeeProto" +
      "sP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yesevi_EmployeePro_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yesevi_EmployeePro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yesevi_EmployeePro_descriptor,
        new java.lang.String[] { "Recid", "Share", "Jobcode", "Title", });
    internal_static_yesevi_EmployeeArray_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_yesevi_EmployeeArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yesevi_EmployeeArray_descriptor,
        new java.lang.String[] { "Employee", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
