// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PATH/file.proto
// Protobuf Java Version: 4.30.2

package com.umut.yesevi.protobuf;

public interface fileMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yesevi.fileMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional bytes fileBytes = 2;</code>
   * @return Whether the fileBytes field is set.
   */
  boolean hasFileBytes();
  /**
   * <code>optional bytes fileBytes = 2;</code>
   * @return The fileBytes.
   */
  com.google.protobuf.ByteString getFileBytes();
}
