// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.27.0

package com.umut.yesevi.protobuf;

public interface PersonArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yesevi.PersonArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .yesevi.PersonPro person = 1;</code>
   */
  java.util.List<com.umut.yesevi.protobuf.PersonPro> 
      getPersonList();
  /**
   * <code>repeated .yesevi.PersonPro person = 1;</code>
   */
  com.umut.yesevi.protobuf.PersonPro getPerson(int index);
  /**
   * <code>repeated .yesevi.PersonPro person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .yesevi.PersonPro person = 1;</code>
   */
  java.util.List<? extends com.umut.yesevi.protobuf.PersonProOrBuilder> 
      getPersonOrBuilderList();
  /**
   * <code>repeated .yesevi.PersonPro person = 1;</code>
   */
  com.umut.yesevi.protobuf.PersonProOrBuilder getPersonOrBuilder(
      int index);
}
