// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person/person.proto
// Protobuf Java Version: 4.31.1

package com.umut.yesevi.protobuf;

@com.google.protobuf.Generated
public final class PersonProtos {
  private PersonProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      PersonProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yesevi_PersonProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yesevi_PersonProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yesevi_PersonProtoArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yesevi_PersonProtoArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023person/person.proto\022\006yesevi\"\213\001\n\013Person" +
      "Proto\022\021\n\004name\030\001 \001(\tH\000\210\001\001\022\025\n\010lastname\030\002 \001" +
      "(\tH\001\210\001\001\022\024\n\007address\030\003 \001(\tH\002\210\001\001\022\021\n\004city\030\004 " +
      "\001(\tH\003\210\001\001B\007\n\005_nameB\013\n\t_lastnameB\n\n\010_addre" +
      "ssB\007\n\005_city\"7\n\020PersonProtoArray\022#\n\006perso" +
      "n\030\001 \003(\0132\023.yesevi.PersonProtoB*\n\030com.umut" +
      ".yesevi.protobufB\014PersonProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yesevi_PersonProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yesevi_PersonProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yesevi_PersonProto_descriptor,
        new java.lang.String[] { "Name", "Lastname", "Address", "City", });
    internal_static_yesevi_PersonProtoArray_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_yesevi_PersonProtoArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yesevi_PersonProtoArray_descriptor,
        new java.lang.String[] { "Person", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
