// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.27.0

package com.umut.yesevi.protobuf;

public interface PersonProOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yesevi.PersonPro)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string lastname = 2;</code>
   * @return Whether the lastname field is set.
   */
  boolean hasLastname();
  /**
   * <code>optional string lastname = 2;</code>
   * @return The lastname.
   */
  java.lang.String getLastname();
  /**
   * <code>optional string lastname = 2;</code>
   * @return The bytes for lastname.
   */
  com.google.protobuf.ByteString
      getLastnameBytes();

  /**
   * <code>optional string address = 3;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional string address = 3;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 3;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>optional string city = 4;</code>
   * @return Whether the city field is set.
   */
  boolean hasCity();
  /**
   * <code>optional string city = 4;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>optional string city = 4;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
