// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person/person.proto
// Protobuf Java Version: 4.31.1

package com.umut.yesevi.protobuf;

@com.google.protobuf.Generated
public interface PersonProtoArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yesevi.PersonProtoArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .yesevi.PersonProto person = 1;</code>
   */
  java.util.List<com.umut.yesevi.protobuf.PersonProto> 
      getPersonList();
  /**
   * <code>repeated .yesevi.PersonProto person = 1;</code>
   */
  com.umut.yesevi.protobuf.PersonProto getPerson(int index);
  /**
   * <code>repeated .yesevi.PersonProto person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .yesevi.PersonProto person = 1;</code>
   */
  java.util.List<? extends com.umut.yesevi.protobuf.PersonProtoOrBuilder> 
      getPersonOrBuilderList();
  /**
   * <code>repeated .yesevi.PersonProto person = 1;</code>
   */
  com.umut.yesevi.protobuf.PersonProtoOrBuilder getPersonOrBuilder(
      int index);
}
