/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.umut.yesevi.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EmployeeAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7552573440168948863L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmployeeAvro\",\"namespace\":\"com.umut.yesevi.avro\",\"fields\":[{\"name\":\"recid\",\"type\":\"double\"},{\"name\":\"share\",\"type\":\"float\"},{\"name\":\"jobcode\",\"type\":\"int\"},{\"name\":\"title\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmployeeAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmployeeAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EmployeeAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EmployeeAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EmployeeAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EmployeeAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EmployeeAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EmployeeAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EmployeeAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private double recid;
  private float share;
  private int jobcode;
  private java.lang.CharSequence title;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmployeeAvro() {}

  /**
   * All-args constructor.
   * @param recid The new value for recid
   * @param share The new value for share
   * @param jobcode The new value for jobcode
   * @param title The new value for title
   */
  public EmployeeAvro(java.lang.Double recid, java.lang.Float share, java.lang.Integer jobcode, java.lang.CharSequence title) {
    this.recid = recid;
    this.share = share;
    this.jobcode = jobcode;
    this.title = title;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return recid;
    case 1: return share;
    case 2: return jobcode;
    case 3: return title;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: recid = (java.lang.Double)value$; break;
    case 1: share = (java.lang.Float)value$; break;
    case 2: jobcode = (java.lang.Integer)value$; break;
    case 3: title = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'recid' field.
   * @return The value of the 'recid' field.
   */
  public double getRecid() {
    return recid;
  }


  /**
   * Sets the value of the 'recid' field.
   * @param value the value to set.
   */
  public void setRecid(double value) {
    this.recid = value;
  }

  /**
   * Gets the value of the 'share' field.
   * @return The value of the 'share' field.
   */
  public float getShare() {
    return share;
  }


  /**
   * Sets the value of the 'share' field.
   * @param value the value to set.
   */
  public void setShare(float value) {
    this.share = value;
  }

  /**
   * Gets the value of the 'jobcode' field.
   * @return The value of the 'jobcode' field.
   */
  public int getJobcode() {
    return jobcode;
  }


  /**
   * Sets the value of the 'jobcode' field.
   * @param value the value to set.
   */
  public void setJobcode(int value) {
    this.jobcode = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Creates a new EmployeeAvro RecordBuilder.
   * @return A new EmployeeAvro RecordBuilder
   */
  public static com.umut.yesevi.avro.EmployeeAvro.Builder newBuilder() {
    return new com.umut.yesevi.avro.EmployeeAvro.Builder();
  }

  /**
   * Creates a new EmployeeAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmployeeAvro RecordBuilder
   */
  public static com.umut.yesevi.avro.EmployeeAvro.Builder newBuilder(com.umut.yesevi.avro.EmployeeAvro.Builder other) {
    if (other == null) {
      return new com.umut.yesevi.avro.EmployeeAvro.Builder();
    } else {
      return new com.umut.yesevi.avro.EmployeeAvro.Builder(other);
    }
  }

  /**
   * Creates a new EmployeeAvro RecordBuilder by copying an existing EmployeeAvro instance.
   * @param other The existing instance to copy.
   * @return A new EmployeeAvro RecordBuilder
   */
  public static com.umut.yesevi.avro.EmployeeAvro.Builder newBuilder(com.umut.yesevi.avro.EmployeeAvro other) {
    if (other == null) {
      return new com.umut.yesevi.avro.EmployeeAvro.Builder();
    } else {
      return new com.umut.yesevi.avro.EmployeeAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for EmployeeAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmployeeAvro>
    implements org.apache.avro.data.RecordBuilder<EmployeeAvro> {

    private double recid;
    private float share;
    private int jobcode;
    private java.lang.CharSequence title;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.umut.yesevi.avro.EmployeeAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.recid)) {
        this.recid = data().deepCopy(fields()[0].schema(), other.recid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.share)) {
        this.share = data().deepCopy(fields()[1].schema(), other.share);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.jobcode)) {
        this.jobcode = data().deepCopy(fields()[2].schema(), other.jobcode);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.title)) {
        this.title = data().deepCopy(fields()[3].schema(), other.title);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing EmployeeAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.umut.yesevi.avro.EmployeeAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.recid)) {
        this.recid = data().deepCopy(fields()[0].schema(), other.recid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.share)) {
        this.share = data().deepCopy(fields()[1].schema(), other.share);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.jobcode)) {
        this.jobcode = data().deepCopy(fields()[2].schema(), other.jobcode);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.title)) {
        this.title = data().deepCopy(fields()[3].schema(), other.title);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'recid' field.
      * @return The value.
      */
    public double getRecid() {
      return recid;
    }


    /**
      * Sets the value of the 'recid' field.
      * @param value The value of 'recid'.
      * @return This builder.
      */
    public com.umut.yesevi.avro.EmployeeAvro.Builder setRecid(double value) {
      validate(fields()[0], value);
      this.recid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'recid' field has been set.
      * @return True if the 'recid' field has been set, false otherwise.
      */
    public boolean hasRecid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'recid' field.
      * @return This builder.
      */
    public com.umut.yesevi.avro.EmployeeAvro.Builder clearRecid() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'share' field.
      * @return The value.
      */
    public float getShare() {
      return share;
    }


    /**
      * Sets the value of the 'share' field.
      * @param value The value of 'share'.
      * @return This builder.
      */
    public com.umut.yesevi.avro.EmployeeAvro.Builder setShare(float value) {
      validate(fields()[1], value);
      this.share = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'share' field has been set.
      * @return True if the 'share' field has been set, false otherwise.
      */
    public boolean hasShare() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'share' field.
      * @return This builder.
      */
    public com.umut.yesevi.avro.EmployeeAvro.Builder clearShare() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'jobcode' field.
      * @return The value.
      */
    public int getJobcode() {
      return jobcode;
    }


    /**
      * Sets the value of the 'jobcode' field.
      * @param value The value of 'jobcode'.
      * @return This builder.
      */
    public com.umut.yesevi.avro.EmployeeAvro.Builder setJobcode(int value) {
      validate(fields()[2], value);
      this.jobcode = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'jobcode' field has been set.
      * @return True if the 'jobcode' field has been set, false otherwise.
      */
    public boolean hasJobcode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'jobcode' field.
      * @return This builder.
      */
    public com.umut.yesevi.avro.EmployeeAvro.Builder clearJobcode() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.umut.yesevi.avro.EmployeeAvro.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.title = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.umut.yesevi.avro.EmployeeAvro.Builder clearTitle() {
      title = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmployeeAvro build() {
      try {
        EmployeeAvro record = new EmployeeAvro();
        record.recid = fieldSetFlags()[0] ? this.recid : (java.lang.Double) defaultValue(fields()[0]);
        record.share = fieldSetFlags()[1] ? this.share : (java.lang.Float) defaultValue(fields()[1]);
        record.jobcode = fieldSetFlags()[2] ? this.jobcode : (java.lang.Integer) defaultValue(fields()[2]);
        record.title = fieldSetFlags()[3] ? this.title : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmployeeAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmployeeAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmployeeAvro>
    READER$ = (org.apache.avro.io.DatumReader<EmployeeAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeDouble(this.recid);

    out.writeFloat(this.share);

    out.writeInt(this.jobcode);

    out.writeString(this.title);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.recid = in.readDouble();

      this.share = in.readFloat();

      this.jobcode = in.readInt();

      this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.recid = in.readDouble();
          break;

        case 1:
          this.share = in.readFloat();
          break;

        case 2:
          this.jobcode = in.readInt();
          break;

        case 3:
          this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










