/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.umut.yesevi.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EmployeeArrayAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4361164408012608149L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmployeeArrayAvro\",\"namespace\":\"com.umut.yesevi.avro\",\"fields\":[{\"name\":\"employees\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"EmployeeAvro\",\"fields\":[{\"name\":\"recid\",\"type\":\"double\"},{\"name\":\"share\",\"type\":\"float\"},{\"name\":\"jobcode\",\"type\":\"int\"},{\"name\":\"title\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmployeeArrayAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmployeeArrayAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EmployeeArrayAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EmployeeArrayAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EmployeeArrayAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EmployeeArrayAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EmployeeArrayAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EmployeeArrayAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EmployeeArrayAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.List<com.umut.yesevi.avro.EmployeeAvro> employees;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmployeeArrayAvro() {}

  /**
   * All-args constructor.
   * @param employees The new value for employees
   */
  public EmployeeArrayAvro(java.util.List<com.umut.yesevi.avro.EmployeeAvro> employees) {
    this.employees = employees;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return employees;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: employees = (java.util.List<com.umut.yesevi.avro.EmployeeAvro>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'employees' field.
   * @return The value of the 'employees' field.
   */
  public java.util.List<com.umut.yesevi.avro.EmployeeAvro> getEmployees() {
    return employees;
  }


  /**
   * Sets the value of the 'employees' field.
   * @param value the value to set.
   */
  public void setEmployees(java.util.List<com.umut.yesevi.avro.EmployeeAvro> value) {
    this.employees = value;
  }

  /**
   * Creates a new EmployeeArrayAvro RecordBuilder.
   * @return A new EmployeeArrayAvro RecordBuilder
   */
  public static com.umut.yesevi.avro.EmployeeArrayAvro.Builder newBuilder() {
    return new com.umut.yesevi.avro.EmployeeArrayAvro.Builder();
  }

  /**
   * Creates a new EmployeeArrayAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmployeeArrayAvro RecordBuilder
   */
  public static com.umut.yesevi.avro.EmployeeArrayAvro.Builder newBuilder(com.umut.yesevi.avro.EmployeeArrayAvro.Builder other) {
    if (other == null) {
      return new com.umut.yesevi.avro.EmployeeArrayAvro.Builder();
    } else {
      return new com.umut.yesevi.avro.EmployeeArrayAvro.Builder(other);
    }
  }

  /**
   * Creates a new EmployeeArrayAvro RecordBuilder by copying an existing EmployeeArrayAvro instance.
   * @param other The existing instance to copy.
   * @return A new EmployeeArrayAvro RecordBuilder
   */
  public static com.umut.yesevi.avro.EmployeeArrayAvro.Builder newBuilder(com.umut.yesevi.avro.EmployeeArrayAvro other) {
    if (other == null) {
      return new com.umut.yesevi.avro.EmployeeArrayAvro.Builder();
    } else {
      return new com.umut.yesevi.avro.EmployeeArrayAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for EmployeeArrayAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmployeeArrayAvro>
    implements org.apache.avro.data.RecordBuilder<EmployeeArrayAvro> {

    private java.util.List<com.umut.yesevi.avro.EmployeeAvro> employees;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.umut.yesevi.avro.EmployeeArrayAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.employees)) {
        this.employees = data().deepCopy(fields()[0].schema(), other.employees);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing EmployeeArrayAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.umut.yesevi.avro.EmployeeArrayAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.employees)) {
        this.employees = data().deepCopy(fields()[0].schema(), other.employees);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'employees' field.
      * @return The value.
      */
    public java.util.List<com.umut.yesevi.avro.EmployeeAvro> getEmployees() {
      return employees;
    }


    /**
      * Sets the value of the 'employees' field.
      * @param value The value of 'employees'.
      * @return This builder.
      */
    public com.umut.yesevi.avro.EmployeeArrayAvro.Builder setEmployees(java.util.List<com.umut.yesevi.avro.EmployeeAvro> value) {
      validate(fields()[0], value);
      this.employees = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'employees' field has been set.
      * @return True if the 'employees' field has been set, false otherwise.
      */
    public boolean hasEmployees() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'employees' field.
      * @return This builder.
      */
    public com.umut.yesevi.avro.EmployeeArrayAvro.Builder clearEmployees() {
      employees = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmployeeArrayAvro build() {
      try {
        EmployeeArrayAvro record = new EmployeeArrayAvro();
        record.employees = fieldSetFlags()[0] ? this.employees : (java.util.List<com.umut.yesevi.avro.EmployeeAvro>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmployeeArrayAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmployeeArrayAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmployeeArrayAvro>
    READER$ = (org.apache.avro.io.DatumReader<EmployeeArrayAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.employees.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.umut.yesevi.avro.EmployeeAvro e0: this.employees) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<com.umut.yesevi.avro.EmployeeAvro> a0 = this.employees;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.umut.yesevi.avro.EmployeeAvro>((int)size0, SCHEMA$.getField("employees").schema());
        this.employees = a0;
      } else a0.clear();
      SpecificData.Array<com.umut.yesevi.avro.EmployeeAvro> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.umut.yesevi.avro.EmployeeAvro>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.umut.yesevi.avro.EmployeeAvro e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.umut.yesevi.avro.EmployeeAvro();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<com.umut.yesevi.avro.EmployeeAvro> a0 = this.employees;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.umut.yesevi.avro.EmployeeAvro>((int)size0, SCHEMA$.getField("employees").schema());
            this.employees = a0;
          } else a0.clear();
          SpecificData.Array<com.umut.yesevi.avro.EmployeeAvro> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.umut.yesevi.avro.EmployeeAvro>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.umut.yesevi.avro.EmployeeAvro e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.umut.yesevi.avro.EmployeeAvro();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










