/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.umut.yesevi.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-02-16")
public class AssetList implements org.apache.thrift.TBase<AssetList, AssetList._Fields>, java.io.Serializable, Cloneable, Comparable<AssetList> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AssetList");

  private static final org.apache.thrift.protocol.TField ASSETS_FIELD_DESC = new org.apache.thrift.protocol.TField("assets", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new AssetListStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new AssetListTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<AssetThrift> assets; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ASSETS((short)1, "assets");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ASSETS
          return ASSETS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ASSETS, new org.apache.thrift.meta_data.FieldMetaData("assets", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AssetThrift.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AssetList.class, metaDataMap);
  }

  public AssetList() {
  }

  public AssetList(
    java.util.List<AssetThrift> assets)
  {
    this();
    this.assets = assets;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AssetList(AssetList other) {
    if (other.isSetAssets()) {
      java.util.List<AssetThrift> __this__assets = new java.util.ArrayList<AssetThrift>(other.assets.size());
      for (AssetThrift other_element : other.assets) {
        __this__assets.add(new AssetThrift(other_element));
      }
      this.assets = __this__assets;
    }
  }

  @Override
  public AssetList deepCopy() {
    return new AssetList(this);
  }

  @Override
  public void clear() {
    this.assets = null;
  }

  public int getAssetsSize() {
    return (this.assets == null) ? 0 : this.assets.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<AssetThrift> getAssetsIterator() {
    return (this.assets == null) ? null : this.assets.iterator();
  }

  public void addToAssets(AssetThrift elem) {
    if (this.assets == null) {
      this.assets = new java.util.ArrayList<AssetThrift>();
    }
    this.assets.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<AssetThrift> getAssets() {
    return this.assets;
  }

  public AssetList setAssets(@org.apache.thrift.annotation.Nullable java.util.List<AssetThrift> assets) {
    this.assets = assets;
    return this;
  }

  public void unsetAssets() {
    this.assets = null;
  }

  /** Returns true if field assets is set (has been assigned a value) and false otherwise */
  public boolean isSetAssets() {
    return this.assets != null;
  }

  public void setAssetsIsSet(boolean value) {
    if (!value) {
      this.assets = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ASSETS:
      if (value == null) {
        unsetAssets();
      } else {
        setAssets((java.util.List<AssetThrift>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ASSETS:
      return getAssets();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ASSETS:
      return isSetAssets();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof AssetList)
      return this.equals((AssetList)that);
    return false;
  }

  public boolean equals(AssetList that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_assets = true && this.isSetAssets();
    boolean that_present_assets = true && that.isSetAssets();
    if (this_present_assets || that_present_assets) {
      if (!(this_present_assets && that_present_assets))
        return false;
      if (!this.assets.equals(that.assets))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetAssets()) ? 131071 : 524287);
    if (isSetAssets())
      hashCode = hashCode * 8191 + assets.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(AssetList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetAssets(), other.isSetAssets());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAssets()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.assets, other.assets);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("AssetList(");
    boolean first = true;

    sb.append("assets:");
    if (this.assets == null) {
      sb.append("null");
    } else {
      sb.append(this.assets);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AssetListStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public AssetListStandardScheme getScheme() {
      return new AssetListStandardScheme();
    }
  }

  private static class AssetListStandardScheme extends org.apache.thrift.scheme.StandardScheme<AssetList> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, AssetList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ASSETS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.assets = new java.util.ArrayList<AssetThrift>(_list0.size);
                @org.apache.thrift.annotation.Nullable AssetThrift _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new AssetThrift();
                  _elem1.read(iprot);
                  struct.assets.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setAssetsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, AssetList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.assets != null) {
        oprot.writeFieldBegin(ASSETS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.assets.size()));
          for (AssetThrift _iter3 : struct.assets)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AssetListTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public AssetListTupleScheme getScheme() {
      return new AssetListTupleScheme();
    }
  }

  private static class AssetListTupleScheme extends org.apache.thrift.scheme.TupleScheme<AssetList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AssetList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetAssets()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetAssets()) {
        {
          oprot.writeI32(struct.assets.size());
          for (AssetThrift _iter4 : struct.assets)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AssetList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.assets = new java.util.ArrayList<AssetThrift>(_list5.size);
          @org.apache.thrift.annotation.Nullable AssetThrift _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new AssetThrift();
            _elem6.read(iprot);
            struct.assets.add(_elem6);
          }
        }
        struct.setAssetsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

