// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: asset.proto
// Protobuf Java Version: 4.27.0

package com.umut.yesevi.protobuf;

public interface AssetProOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yesevi.AssetPro)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional double id = 1;</code>
   * @return The id.
   */
  double getId();

  /**
   * <code>optional float rationum = 2;</code>
   * @return Whether the rationum field is set.
   */
  boolean hasRationum();
  /**
   * <code>optional float rationum = 2;</code>
   * @return The rationum.
   */
  float getRationum();

  /**
   * <code>optional int32 barcode = 3;</code>
   * @return Whether the barcode field is set.
   */
  boolean hasBarcode();
  /**
   * <code>optional int32 barcode = 3;</code>
   * @return The barcode.
   */
  int getBarcode();

  /**
   * <code>optional int32 itemnum = 4;</code>
   * @return Whether the itemnum field is set.
   */
  boolean hasItemnum();
  /**
   * <code>optional int32 itemnum = 4;</code>
   * @return The itemnum.
   */
  int getItemnum();
}
