// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: asset.proto
// Protobuf Java Version: 4.27.0

package com.umut.yesevi.protobuf;

public interface AssetArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yesevi.AssetArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .yesevi.AssetPro asset = 1;</code>
   */
  java.util.List<com.umut.yesevi.protobuf.AssetPro> 
      getAssetList();
  /**
   * <code>repeated .yesevi.AssetPro asset = 1;</code>
   */
  com.umut.yesevi.protobuf.AssetPro getAsset(int index);
  /**
   * <code>repeated .yesevi.AssetPro asset = 1;</code>
   */
  int getAssetCount();
  /**
   * <code>repeated .yesevi.AssetPro asset = 1;</code>
   */
  java.util.List<? extends com.umut.yesevi.protobuf.AssetProOrBuilder> 
      getAssetOrBuilderList();
  /**
   * <code>repeated .yesevi.AssetPro asset = 1;</code>
   */
  com.umut.yesevi.protobuf.AssetProOrBuilder getAssetOrBuilder(
      int index);
}
