// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: asset/asset.proto
// Protobuf Java Version: 4.31.1

package com.umut.yesevi.protobuf;

/**
 * Protobuf type {@code yesevi.AssetProtoArray}
 */
@com.google.protobuf.Generated
public final class AssetProtoArray extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:yesevi.AssetProtoArray)
    AssetProtoArrayOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      AssetProtoArray.class.getName());
  }
  // Use AssetProtoArray.newBuilder() to construct.
  private AssetProtoArray(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AssetProtoArray() {
    asset_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.umut.yesevi.protobuf.AssetProtos.internal_static_yesevi_AssetProtoArray_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.umut.yesevi.protobuf.AssetProtos.internal_static_yesevi_AssetProtoArray_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.umut.yesevi.protobuf.AssetProtoArray.class, com.umut.yesevi.protobuf.AssetProtoArray.Builder.class);
  }

  public static final int ASSET_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.umut.yesevi.protobuf.AssetProto> asset_;
  /**
   * <code>repeated .yesevi.AssetProto asset = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.umut.yesevi.protobuf.AssetProto> getAssetList() {
    return asset_;
  }
  /**
   * <code>repeated .yesevi.AssetProto asset = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.umut.yesevi.protobuf.AssetProtoOrBuilder> 
      getAssetOrBuilderList() {
    return asset_;
  }
  /**
   * <code>repeated .yesevi.AssetProto asset = 1;</code>
   */
  @java.lang.Override
  public int getAssetCount() {
    return asset_.size();
  }
  /**
   * <code>repeated .yesevi.AssetProto asset = 1;</code>
   */
  @java.lang.Override
  public com.umut.yesevi.protobuf.AssetProto getAsset(int index) {
    return asset_.get(index);
  }
  /**
   * <code>repeated .yesevi.AssetProto asset = 1;</code>
   */
  @java.lang.Override
  public com.umut.yesevi.protobuf.AssetProtoOrBuilder getAssetOrBuilder(
      int index) {
    return asset_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < asset_.size(); i++) {
      output.writeMessage(1, asset_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < asset_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, asset_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.umut.yesevi.protobuf.AssetProtoArray)) {
      return super.equals(obj);
    }
    com.umut.yesevi.protobuf.AssetProtoArray other = (com.umut.yesevi.protobuf.AssetProtoArray) obj;

    if (!getAssetList()
        .equals(other.getAssetList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAssetCount() > 0) {
      hash = (37 * hash) + ASSET_FIELD_NUMBER;
      hash = (53 * hash) + getAssetList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.umut.yesevi.protobuf.AssetProtoArray parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.umut.yesevi.protobuf.AssetProtoArray parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.umut.yesevi.protobuf.AssetProtoArray parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.umut.yesevi.protobuf.AssetProtoArray parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.umut.yesevi.protobuf.AssetProtoArray parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.umut.yesevi.protobuf.AssetProtoArray parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.umut.yesevi.protobuf.AssetProtoArray parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.umut.yesevi.protobuf.AssetProtoArray parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.umut.yesevi.protobuf.AssetProtoArray parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.umut.yesevi.protobuf.AssetProtoArray parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.umut.yesevi.protobuf.AssetProtoArray parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.umut.yesevi.protobuf.AssetProtoArray parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.umut.yesevi.protobuf.AssetProtoArray prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code yesevi.AssetProtoArray}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yesevi.AssetProtoArray)
      com.umut.yesevi.protobuf.AssetProtoArrayOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.umut.yesevi.protobuf.AssetProtos.internal_static_yesevi_AssetProtoArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.umut.yesevi.protobuf.AssetProtos.internal_static_yesevi_AssetProtoArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.umut.yesevi.protobuf.AssetProtoArray.class, com.umut.yesevi.protobuf.AssetProtoArray.Builder.class);
    }

    // Construct using com.umut.yesevi.protobuf.AssetProtoArray.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (assetBuilder_ == null) {
        asset_ = java.util.Collections.emptyList();
      } else {
        asset_ = null;
        assetBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.umut.yesevi.protobuf.AssetProtos.internal_static_yesevi_AssetProtoArray_descriptor;
    }

    @java.lang.Override
    public com.umut.yesevi.protobuf.AssetProtoArray getDefaultInstanceForType() {
      return com.umut.yesevi.protobuf.AssetProtoArray.getDefaultInstance();
    }

    @java.lang.Override
    public com.umut.yesevi.protobuf.AssetProtoArray build() {
      com.umut.yesevi.protobuf.AssetProtoArray result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.umut.yesevi.protobuf.AssetProtoArray buildPartial() {
      com.umut.yesevi.protobuf.AssetProtoArray result = new com.umut.yesevi.protobuf.AssetProtoArray(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.umut.yesevi.protobuf.AssetProtoArray result) {
      if (assetBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          asset_ = java.util.Collections.unmodifiableList(asset_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.asset_ = asset_;
      } else {
        result.asset_ = assetBuilder_.build();
      }
    }

    private void buildPartial0(com.umut.yesevi.protobuf.AssetProtoArray result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.umut.yesevi.protobuf.AssetProtoArray) {
        return mergeFrom((com.umut.yesevi.protobuf.AssetProtoArray)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.umut.yesevi.protobuf.AssetProtoArray other) {
      if (other == com.umut.yesevi.protobuf.AssetProtoArray.getDefaultInstance()) return this;
      if (assetBuilder_ == null) {
        if (!other.asset_.isEmpty()) {
          if (asset_.isEmpty()) {
            asset_ = other.asset_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAssetIsMutable();
            asset_.addAll(other.asset_);
          }
          onChanged();
        }
      } else {
        if (!other.asset_.isEmpty()) {
          if (assetBuilder_.isEmpty()) {
            assetBuilder_.dispose();
            assetBuilder_ = null;
            asset_ = other.asset_;
            bitField0_ = (bitField0_ & ~0x00000001);
            assetBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetAssetFieldBuilder() : null;
          } else {
            assetBuilder_.addAllMessages(other.asset_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.umut.yesevi.protobuf.AssetProto m =
                  input.readMessage(
                      com.umut.yesevi.protobuf.AssetProto.parser(),
                      extensionRegistry);
              if (assetBuilder_ == null) {
                ensureAssetIsMutable();
                asset_.add(m);
              } else {
                assetBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.umut.yesevi.protobuf.AssetProto> asset_ =
      java.util.Collections.emptyList();
    private void ensureAssetIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        asset_ = new java.util.ArrayList<com.umut.yesevi.protobuf.AssetProto>(asset_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.umut.yesevi.protobuf.AssetProto, com.umut.yesevi.protobuf.AssetProto.Builder, com.umut.yesevi.protobuf.AssetProtoOrBuilder> assetBuilder_;

    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public java.util.List<com.umut.yesevi.protobuf.AssetProto> getAssetList() {
      if (assetBuilder_ == null) {
        return java.util.Collections.unmodifiableList(asset_);
      } else {
        return assetBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public int getAssetCount() {
      if (assetBuilder_ == null) {
        return asset_.size();
      } else {
        return assetBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public com.umut.yesevi.protobuf.AssetProto getAsset(int index) {
      if (assetBuilder_ == null) {
        return asset_.get(index);
      } else {
        return assetBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public Builder setAsset(
        int index, com.umut.yesevi.protobuf.AssetProto value) {
      if (assetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAssetIsMutable();
        asset_.set(index, value);
        onChanged();
      } else {
        assetBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public Builder setAsset(
        int index, com.umut.yesevi.protobuf.AssetProto.Builder builderForValue) {
      if (assetBuilder_ == null) {
        ensureAssetIsMutable();
        asset_.set(index, builderForValue.build());
        onChanged();
      } else {
        assetBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public Builder addAsset(com.umut.yesevi.protobuf.AssetProto value) {
      if (assetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAssetIsMutable();
        asset_.add(value);
        onChanged();
      } else {
        assetBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public Builder addAsset(
        int index, com.umut.yesevi.protobuf.AssetProto value) {
      if (assetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAssetIsMutable();
        asset_.add(index, value);
        onChanged();
      } else {
        assetBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public Builder addAsset(
        com.umut.yesevi.protobuf.AssetProto.Builder builderForValue) {
      if (assetBuilder_ == null) {
        ensureAssetIsMutable();
        asset_.add(builderForValue.build());
        onChanged();
      } else {
        assetBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public Builder addAsset(
        int index, com.umut.yesevi.protobuf.AssetProto.Builder builderForValue) {
      if (assetBuilder_ == null) {
        ensureAssetIsMutable();
        asset_.add(index, builderForValue.build());
        onChanged();
      } else {
        assetBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public Builder addAllAsset(
        java.lang.Iterable<? extends com.umut.yesevi.protobuf.AssetProto> values) {
      if (assetBuilder_ == null) {
        ensureAssetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, asset_);
        onChanged();
      } else {
        assetBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public Builder clearAsset() {
      if (assetBuilder_ == null) {
        asset_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        assetBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public Builder removeAsset(int index) {
      if (assetBuilder_ == null) {
        ensureAssetIsMutable();
        asset_.remove(index);
        onChanged();
      } else {
        assetBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public com.umut.yesevi.protobuf.AssetProto.Builder getAssetBuilder(
        int index) {
      return internalGetAssetFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public com.umut.yesevi.protobuf.AssetProtoOrBuilder getAssetOrBuilder(
        int index) {
      if (assetBuilder_ == null) {
        return asset_.get(index);  } else {
        return assetBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public java.util.List<? extends com.umut.yesevi.protobuf.AssetProtoOrBuilder> 
         getAssetOrBuilderList() {
      if (assetBuilder_ != null) {
        return assetBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(asset_);
      }
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public com.umut.yesevi.protobuf.AssetProto.Builder addAssetBuilder() {
      return internalGetAssetFieldBuilder().addBuilder(
          com.umut.yesevi.protobuf.AssetProto.getDefaultInstance());
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public com.umut.yesevi.protobuf.AssetProto.Builder addAssetBuilder(
        int index) {
      return internalGetAssetFieldBuilder().addBuilder(
          index, com.umut.yesevi.protobuf.AssetProto.getDefaultInstance());
    }
    /**
     * <code>repeated .yesevi.AssetProto asset = 1;</code>
     */
    public java.util.List<com.umut.yesevi.protobuf.AssetProto.Builder> 
         getAssetBuilderList() {
      return internalGetAssetFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.umut.yesevi.protobuf.AssetProto, com.umut.yesevi.protobuf.AssetProto.Builder, com.umut.yesevi.protobuf.AssetProtoOrBuilder> 
        internalGetAssetFieldBuilder() {
      if (assetBuilder_ == null) {
        assetBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.umut.yesevi.protobuf.AssetProto, com.umut.yesevi.protobuf.AssetProto.Builder, com.umut.yesevi.protobuf.AssetProtoOrBuilder>(
                asset_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        asset_ = null;
      }
      return assetBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:yesevi.AssetProtoArray)
  }

  // @@protoc_insertion_point(class_scope:yesevi.AssetProtoArray)
  private static final com.umut.yesevi.protobuf.AssetProtoArray DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.umut.yesevi.protobuf.AssetProtoArray();
  }

  public static com.umut.yesevi.protobuf.AssetProtoArray getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AssetProtoArray>
      PARSER = new com.google.protobuf.AbstractParser<AssetProtoArray>() {
    @java.lang.Override
    public AssetProtoArray parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AssetProtoArray> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AssetProtoArray> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.umut.yesevi.protobuf.AssetProtoArray getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

